version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 613536206275.dkr.ecr.eu-west-1.amazonaws.com
  build:
    commands:
      - docker build -t expresshello .
      - docker tag expresshello 613536206275.dkr.ecr.eu-west-1.amazonaws.com/expresshello:latest
  post_build:
    commands:
      - docker push 613536206275.dkr.ecr.eu-west-1.amazonaws.com/expresshello:latest
      - printf '[{"name":express-task,"imageUri":"%s"}]' 613536206275.dkr.ecr.eu-west-1.amazonaws.com/expresshello:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
